### PR TITLE
A Tale of Performance - JavaScript, Rust, and WebAssembly

### PR DESCRIPTION
**Pull request by twilco**
This PR adds my blog post about Rust and WebAssembly.  Here's an excerpt to describe this post in brief:

> Embark on a journey of optimization with me, learning in great detail about Rust, WebAssembly, and lots more along the way. We will compare and contrast multiple approaches to solving a performance problem, from native browser APIs to both naive and complex Rust and WebAssembly implementations.

This PR also changes some site styling:
* The default font site-wide is now Helvetica Neue to comply with brand guidelines.
* Update various header and link colors to comply with brand guidelines.
* Increase spacing above and below "Widen engineering" in global site header to comply with brand guidelines.
* Add `blockquote` styling, which somehow didn't already exist.

### CODE REVIEW

**Comment by dbeg** [comment]
Helpful preview of the actual article: https://github.com/Widen/widen.github.io/blob/9c8947df12a2ca97e539bdf96a6458c8336c6712/_posts/2019-01-14-A-Tale-of-Performance---Javascript%2C-Rust%2C-and-WebAssembly.md

**Comment by twilco** [comment]
Thanks for that preview!  Yes, all styling changes are a result of working with Danielle Templeton.

**Comment by dbeg** [comment]
Might also be worth passing your draft on to Amanda for a technical writing review? I think she's reviewed some of these posts in the past?

**Comment by twilco** [comment]
Sending it off to her this morning 👍

**Comment by bdotte** [comment]
💯 

This is a really cool post, I like the depth and code samples, and anything bleeding-edge like Rust+WebAssembly tends to attract attention (similar to Ray's first post).

I like the background you have given on why Rust matches well to WebAssembly vs. others due to a large download required, etc.

I enjoyed the section headings, they are humorous and descriptive. I haven't come up with anything I would specifically try to improve, maybe a followup post is in order on what the "right way" looks like!

**Comment by twilco** [comment]
@bdotte Thanks for that feedback!  Glad you liked it.

Amanda has reviewed the post and made technical corrections, and Kevin B and Matt F have signed off on the post from a confidential information perspective.  Is there anything else that should be checked, or is this good to go?

**Comment by bdotte** [comment]
LGTM

**Comment by twilco** [comment]
Cool!  Merging (and therefore deploying) 🚀

**Pull request merged**
